Repository pomazkovanton/noiceland, pull requests merged in 2023-02, with the labels that each got.

#5 pull request: добавить переменные цветов
  src/index.html
  src/styles/commons/variables.css
  src/styles/pages/index.css
Labels: feat

#18 pull request: добавить шрифты
  .husky/pre-commit
  package-lock.json
  package.json
  src/assets/fonts/LibreFranklin-Bold.woff
  src/assets/fonts/LibreFranklin-Bold.woff2
  src/assets/fonts/LibreFranklin-Regular.woff
  src/assets/fonts/LibreFranklin-Regular.woff2
  src/assets/fonts/SourceSerifpro-regular-webfont.woff
  src/assets/fonts/SourceSerifpro-regular-webfont.woff2
  src/assets/fonts/Tenorsans-regular-webfont.woff
  src/assets/fonts/Tenorsans-regular-webfont.woff2
  src/styles/commons/fonts.css
  src/styles/commons/variables.css
  src/styles/pages/index.css
Labels: feat

#19 pull request: импортировать все изображения из проекта
  src/accets/images/large-card_1_onojeghuo.jpg
  src/accets/images/large-card_2_ortiz.jpg
  src/accets/images/large-card_3_gottlieb.jpg
  src/accets/images/large-card_4_lueilwitz.jpg
  src/accets/images/logo_black-text.svg
  src/accets/images/medium-card_1_ortiz.jpg
  src/accets/images/medium-card_2_ondricka.jpg
  src/accets/images/medium-card_3_lueilwitz.jpg
  src/accets/images/medium-card_4_lueilwitz.jpg
  src/accets/images/medium-card_5_brekke.jpg
  src/accets/images/medium-card_6_torphy.jpg
  src/accets/images/small-card_8_bartell.jpg
  src/accets/images/top-card_torphy.jpg
Labels: feat

#22 pull request: перенести все изображения в папку assets
  src/assets/images/large-card_1_onojeghuo.jpg
  src/assets/images/large-card_2_ortiz.jpg
  src/assets/images/large-card_3_gottlieb.jpg
  src/assets/images/large-card_4_lueilwitz.jpg
  src/assets/images/logo_black-text.svg
  src/assets/images/medium-card_1_ortiz.jpg
  src/assets/images/medium-card_2_ondricka.jpg
  src/assets/images/medium-card_3_lueilwitz.jpg
  src/assets/images/medium-card_4_lueilwitz.jpg
  src/assets/images/medium-card_5_brekke.jpg
  src/assets/images/medium-card_6_torphy.jpg
  src/assets/images/small-card_8_bartell.jpg
  src/assets/images/top-card_torphy.jpg
Labels: fix

#27 pull request: добавить normolize css
  .stylelintrc.json
  src/styles/pages/index.css
  src/styles/vendor/normalize.css
Labels: feat, style, build

#23 pull request: Добавить стили ссылкам
  .stylelintrc.json
  src/components/UI/link/_color/link_color_dark.css
  src/components/UI/link/_color/link_color_light.css
  src/components/UI/link/link.css
  src/components/UI/link/link.html
  src/styles/commons/fonts.css
  src/styles/commons/variables.css
  src/styles/pages/index.css
Labels: style

#28 pull request: заполнить шапку сайта
  src/assets/images/favicon.svg
  src/index.html
Labels: doc, feat

#24 pull request: добавить универсальные стили для блока Text
  src/components/UI/text/_type/text_type_author.css
  src/components/UI/text/_type/text_type_paragraph.css
  src/components/UI/text/_type/text_type_subtitle.css
  src/components/UI/text/_type/text_type_theme.css
  src/components/UI/text/_type/text_type_title.css
  src/components/UI/text/text.css
  src/components/UI/text/text.html
  src/styles/pages/index.css
Labels: style

#29 fix: добавить участника в проект #13
  README.md
Labels: fix

#30 pull request: сделать стили для формы подписки
  src/components/UI/link/link.html
  src/components/form/__button/form__button.css
  src/components/form/__email/form__email.css
  src/components/form/form.css
  src/components/form/form.html
  src/styles/pages/index.css
Labels: style

#32 pull request: добавить стили для логотипа
  src/assets/images/logo_black-text.svg
  src/components/UI/logo/_theme/logo_theme_dark.css
  src/components/UI/logo/_theme/logo_theme_light.css
  src/components/UI/logo/logo.css
  src/components/UI/logo/logo.html
  src/styles/pages/index.css
Labels: style

#33 pull request: добавить шапку сайта
  src/components/header/__container/header__container.css
  src/components/header/__logo-link/header__logo-link.css
  src/components/header/__menu/header__menu.css
  src/components/header/header.css
  src/index.html
  src/styles/pages/index.css
Labels: feat

#40 pull request: поменять контакт разработчика в README.md
  README.md
Labels: fix
