Repository pomazkovanton/noiceland, pull requests merged in 2023-03, with the labels that each got.

#42 pull request: добавить стили для карточек
  src/components/card/__info-box/_place/card__info-box_place_main.css
  src/components/card/__info-box/card__info-box.css
  src/components/card/__paparagraph/card__paparagraph.css
  src/components/card/__picture/_place/card__picture_place_current.css
  src/components/card/__picture/_place/card__picture_place_featured.css
  src/components/card/__picture/_place/card__picture_place_latest.css
  src/components/card/__picture/_place/card__picture_place_main.css
  src/components/card/__picture/card__picture.css
  src/components/card/__subtitle/card__subtitle.css
  src/components/card/__theme/card__theme.css
  src/components/card/__title/card__title.css
  src/components/card/_place/card_place_current.css
  src/components/card/_place/card_place_featured.css
  src/components/card/_place/card_place_latest.css
  src/components/card/_place/card_place_main.css
  src/components/card/card.css
  src/components/card/card.html
Labels: style

#43 pull-request: добавить стили для списков с навигацией
  src/components/nav-list/__item/_place/nav-list_place_information.css
  src/components/nav-list/__item/nav-list__item.css
  src/components/nav-list/__title/_place/nav-list__title_place_categories.css
  src/components/nav-list/__title/nav-list__title.css
  src/components/nav-list/_place/nav-list_place_categories.css
  src/components/nav-list/nav-list.css
  src/components/nav-list/nav-list.html
Labels: style

#45 pull-request: исправить ошибку в подключении шрифтов в text
  src/components/UI/text/_type/text_type_author.css
  src/components/UI/text/_type/text_type_paragraph.css
  src/components/UI/text/_type/text_type_subtitle.css
  src/components/UI/text/_type/text_type_theme.css
  src/components/UI/text/_type/text_type_title.css
  src/styles/commons/fonts.css
Labels: fix

#46 pull-request: добавить секцию с рекомендуемыми постами
  .prettierrc.json
  src/components/featured-posts/__gallery/featured-posts__gallery.css
  src/components/featured-posts/__link/fearured-posts__link.css
  src/components/featured-posts/__post/featured-posts__post.css
  src/components/featured-posts/__title/featured-posts__title.css
  src/components/featured-posts/featured-posts.css
  src/index.html
  src/styles/pages/index.css
Labels: feat
